let a = Math.round(Math.random() * 100)
alert('Sizda xozi random sonlar chiqishni boshledi')
alert(`Random orqali chiqqan son: ${a}`)
confirm('Biz random sonni 2 ga kopaytirmoqchimiz va bolmoqchimiz!')
alert(`Random orqali chiqqan son: ${a} edi` + `\nBiz uni 2 ga kopaytirib ${a * 2} sonini chiqardik` + `\nVa shu sonni 2 ga bolib: ${a / 2} chiqardik` + `\nVa shu sonni 3 ga bolganda qoldiq: ${a % 3} sonini chiqardik`)